In [1]:
import numpy as np

In [2]:
sudoku = -np.ones((9,9))

In [3]:
grille=np.array([
    [0,0,0,0,6,0,0,3,0],
    [2,0,7,3,8,0,0,4,0],
    [6,0,0,0,0,0,0,2,0],
    [3,0,0,1,4,5,2,0,0],
    [5,6,1,2,9,0,0,7,0],
    [0,0,9,0,7,0,0,0,1],
    [8,0,2,5,1,0,6,0,4],
    [0,4,0,9,3,6,8,0,0],
    [0,9,0,0,0,4,3,0,7]]
)

In [4]:
print(grille)

[[0 0 0 0 6 0 0 3 0]
 [2 0 7 3 8 0 0 4 0]
 [6 0 0 0 0 0 0 2 0]
 [3 0 0 1 4 5 2 0 0]
 [5 6 1 2 9 0 0 7 0]
 [0 0 9 0 7 0 0 0 1]
 [8 0 2 5 1 0 6 0 4]
 [0 4 0 9 3 6 8 0 0]
 [0 9 0 0 0 4 3 0 7]]
